/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatN8n: typeof import('./components/chat/n8n/Index.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    MarkdownRenderer: typeof import('./components/markdown/Renderer.vue')['default']
    N8nEmbeddedChatInterface: typeof import('./components/N8nEmbeddedChatInterface.vue')['default']
    Thinking: typeof import('./components/Thinking.vue')['default']
    UiAccordionAccordion: typeof import('./components/ui/accordion/Accordion.vue')['default']
    UiAccordionAccordionContent: typeof import('./components/ui/accordion/AccordionContent.vue')['default']
    UiAccordionAccordionItem: typeof import('./components/ui/accordion/AccordionItem.vue')['default']
    UiAccordionAccordionTrigger: typeof import('./components/ui/accordion/AccordionTrigger.vue')['default']
    UiBadgeBadge: typeof import('./components/ui/badge/Badge.vue')['default']
    UiButtonButton: typeof import('./components/ui/button/Button.vue')['default']
    UiDropdownMenuDropdownMenu: typeof import('./components/ui/dropdown-menu/DropdownMenu.vue')['default']
    UiDropdownMenuDropdownMenuCheckboxItem: typeof import('./components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue')['default']
    UiDropdownMenuDropdownMenuContent: typeof import('./components/ui/dropdown-menu/DropdownMenuContent.vue')['default']
    UiDropdownMenuDropdownMenuGroup: typeof import('./components/ui/dropdown-menu/DropdownMenuGroup.vue')['default']
    UiDropdownMenuDropdownMenuItem: typeof import('./components/ui/dropdown-menu/DropdownMenuItem.vue')['default']
    UiDropdownMenuDropdownMenuLabel: typeof import('./components/ui/dropdown-menu/DropdownMenuLabel.vue')['default']
    UiDropdownMenuDropdownMenuRadioGroup: typeof import('./components/ui/dropdown-menu/DropdownMenuRadioGroup.vue')['default']
    UiDropdownMenuDropdownMenuRadioItem: typeof import('./components/ui/dropdown-menu/DropdownMenuRadioItem.vue')['default']
    UiDropdownMenuDropdownMenuSeparator: typeof import('./components/ui/dropdown-menu/DropdownMenuSeparator.vue')['default']
    UiDropdownMenuDropdownMenuShortcut: typeof import('./components/ui/dropdown-menu/DropdownMenuShortcut.vue')['default']
    UiDropdownMenuDropdownMenuSub: typeof import('./components/ui/dropdown-menu/DropdownMenuSub.vue')['default']
    UiDropdownMenuDropdownMenuSubContent: typeof import('./components/ui/dropdown-menu/DropdownMenuSubContent.vue')['default']
    UiDropdownMenuDropdownMenuSubTrigger: typeof import('./components/ui/dropdown-menu/DropdownMenuSubTrigger.vue')['default']
    UiDropdownMenuDropdownMenuTrigger: typeof import('./components/ui/dropdown-menu/DropdownMenuTrigger.vue')['default']
    UiInputInput: typeof import('./components/ui/input/Input.vue')['default']
    UiResizeHandle: typeof import('./components/ui/ResizeHandle.vue')['default']
    UiTextareaTextarea: typeof import('./components/ui/textarea/Textarea.vue')['default']
    UiToastToast: typeof import('./components/ui/toast/Toast.vue')['default']
    UiToastToastAction: typeof import('./components/ui/toast/ToastAction.vue')['default']
    UiToastToastClose: typeof import('./components/ui/toast/ToastClose.vue')['default']
    UiToastToastDescription: typeof import('./components/ui/toast/ToastDescription.vue')['default']
    UiToastToaster: typeof import('./components/ui/toast/Toaster.vue')['default']
    UiToastToastProvider: typeof import('./components/ui/toast/ToastProvider.vue')['default']
    UiToastToastTitle: typeof import('./components/ui/toast/ToastTitle.vue')['default']
    UiToastToastViewport: typeof import('./components/ui/toast/ToastViewport.vue')['default']
  }
}
